ROW_LENGTH = 128
FIX_ROW_LENGTH = 64
MANUAL_SIZE = 10
LEAST_VOLUME_SIZE = 100000
NONE_SENSE_DATA_TYPE = 100
NOT_ORDER_DATA_TYPE = 0
CHECK_IMAGE_GROUP_SIZE = 10
ORDER_TO_NOT_ORDER = 100
RNN_MODEL_NAME ="rnn_model.h5"
LSTM_MODEL_NAME ="lstm_model.h5"
RNN_LSTM_MIX_MODEL_NAME ="rnn_lstm_mix_model.h5"

GENERAL_MODEL_NAME = str(FIX_ROW_LENGTH) + '_' + RNN_MODEL_NAME